
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-09
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-09
pull_requests: [{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"right-align-profit","number":72,"title":"Elijah - Fixed Profit Table right aligment","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/72"},{"author":{"id":"U_kgDOB7-k5A","is_bot":false,"login":"SexyJesusFreak","name":"Nathaniel Mitter"},"headRefName":"39-feature-make-announcements-form-and-table-visible-on-play-page","number":69,"title":"NM - made feature make announcements form and table visible on play page","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/69"},{"author":{"id":"U_kgDOBt0KgA","is_bot":false,"login":"azhe12345","name":"Hongtao Li"},"headRefName":"Hontao-stryker-exceptions","number":68,"title":"Hongtao - Full mutation coverage for ProfitsTable.js and CommonsCard.js","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/68"},{"author":{"id":"U_kgDOBtFGRA","is_bot":false,"login":"neil-roy","name":""},"headRefName":"15-announcement-form","number":67,"title":"15 announcement form","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/67"},{"author":{"id":"U_kgDOBt0KgA","is_bot":false,"login":"azhe12345","name":"Hongtao Li"},"headRefName":"Hongtao-Course-Put","number":64,"title":"Hongtao course put and delete ","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/64"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"Alec-StudentsCreatePage","number":58,"title":"Alec - Added Create Students page","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/58"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"Alec-StudentsEditPage","number":57,"title":"Alec - Added Edit Page for students","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/57"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"Alec-StudentsIndex","number":54,"title":"Alec - Added Index Page for Students","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/54"}]
