
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-09
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-09
pull_requests: [{"author":{"id":"U_kgDOBtFE9g","is_bot":false,"login":"TomShangguan","name":""},"headRefName":"tom-course-database-table","number":37,"title":"ADD DB TABLE FOR COURSES IN THE BACKEND","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/37"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"Alec-LeaderboardSortByTotalWealth","number":25,"title":"Alec - Fixed Leaderboard sorting by total wealth","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/25"}]
