
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-happycows-f24-09
owner: ucsb-cs156-f24
repo_name: proj-happycows-f24-09
pull_requests: [{"author":{"id":"U_kgDOBtFE9g","is_bot":false,"login":"TomShangguan","name":""},"headRefName":"tom-BUG-profits-table","number":12,"title":"Tom bug profits table","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/12"},{"author":{"id":"U_kgDOBtFE9g","is_bot":false,"login":"TomShangguan","name":""},"headRefName":"tom-MINORUXFIX-Inconsistent-capitalization","number":11,"title":"UIFIX","url":"https://github.com/ucsb-cs156-f24/proj-happycows-f24-09/pull/11"}]
